// UK lang variables

tinyMCE.addToLang('advcode',{
    chars : 'Insert special char',
    comment : 'Insert comment',
    div : 'Insert DIV-Element',
    head1 : 'Headline 1',
    head2 : 'Headline 2',
    head3 : 'Headline 3',
    head4 : 'Headline 4',
    head5 : 'Headline 5',
    head6 : 'Headline 6',
    image : 'Insert image',
    image_prompt : 'Please insert the URL/source of the image',
    italic : 'Italic',
    linebreak : 'Linebreak',
    linenumbers : 'Zeilennummern',
    list : 'Unordered list',
    listitem : 'New list item',
    mail : 'E-Mail link',
    media : 'Embeded media',
    mail_prompt : 'Please insert mail address',
    mail_title : 'Send e-mail to',
    numlist : 'Numbered list',
    pagelink : 'Insert link',
    pagelink_prompt : 'Please insert the URL to the linked file',
    paragraph : 'New paragraph',
    redo : 'Redo',
    script : 'Insert script',
    space : 'Non-breaking space',
    strong : 'Bold',
    table : 'Insert table',
    tablecell : 'Insert new table cell',
    tablecellhead : 'Insert new table cell head',
    tablerow : 'Insert new table row',
    textsub : 'Subscript',
    textsup : 'Superscript',
    underline : 'Underlinedn',
    undo : 'Undo',
    delta_width : 0
});
